[platformio]
default_envs = esp32-c3-supermini
src_dir = main

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
board_build.flash_mode = dio
board_build.sdkconfig_defaults = sdkconfig.defaults,sdkconfig.defaults.esp32c3
